name: 'Terraform Plan and Apply'

on:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    environment: DEV
    name: 'Terraform plan'
    
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: 'echo workspace'
        run: |
          echo "github.workspace"
          echo ${{ github.workspace }}
          echo "GITHUB_WORKSPACE"
          echo $GITHUB_WORKSPACE
          echo "my working directory"
          echo $MY_WORK_DIR
          ls -al
        
      - name: 'Install terraform'
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get install terraform
    
      - name: 'Verify the installation'
        run: |
          terraform -help
          terraform -help plan

      - name: 'Install and validate TFLINT'
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --help
    

      - name: 'Initialize terraform'
        run: terraform init
        
      - name: 'Terraform plan'
        run: terraform plan


  terraform_apply:
    environment: DEV
    name: 'Terraform apply'
    needs: [terraform_plan]
    
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest

    steps:
      - name: 'Terraform apply'
        run: terraform apply -auto-approve

      - name: 'terraform state'
        run: terraform state list