name: 'Terraform Import multiple resources into state file'

on:
  workflow_dispatch:
    inputs:
      Configuration:
        type: choice
        description: 'Select Configuration'
        options:
          - 'Network'
          - 'AKS'
          - 'functionapp'
          - 'logicapp'
      Environment:
        type: choice
        description: 'Select Environment'
        options:
          - 'DEV'
          - 'UAT'
          - 'PROD'
      TerraformEnvironment:
        type: choice
        description: 'Select Terraform Environment'
        options:
          - 'DEV'
          - 'UAT'
          - 'PROD'
      CSF_FILE:
        type: string
        description: 'Enter the path to the CSV file containing resource import details'
        default: "../../.github/workflows/resources_to_import.csv"
        required: true


  # push:
  #   branches:
  #     - main
  

jobs:
  terraform_plan_after_import:
    environment: ${{github.event.inputs.Environment}}
    name: 'Terraform plan'
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TerraformEnvironment: ${{github.event.inputs.TerraformEnvironment}}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infrastructure/${{ github.event.inputs.Configuration }}
    
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: 'echo workspace'
        run: |
          pwd
          echo "github.workspace"
          echo ${{ github.workspace }}
          echo "GITHUB_WORKSPACE"
          echo $GITHUB_WORKSPACE
          echo "my working directory"
          echo $MY_WORK_DIR
          ls -al
        
      - name: 'Install terraform'
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get install terraform
    
      - name: 'Verify the installation'
        run: |
          terraform -help
          terraform -help plan

      # - name: 'Install and validate TFLINT'
      #   run: |
      #     curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      #     tflint --help
    

      - name: 'Initialize terraform'
        run: terraform init -backend-config=environments/${{ github.event.inputs.TerraformEnvironment }}/${{ github.event.inputs.TerraformEnvironment }}.tfbackend -var-file=environments/${{ github.event.inputs.TerraformEnvironment }}/${{ github.event.inputs.TerraformEnvironment }}.tfvars
        working-directory: infrastructure/${{ github.event.inputs.Configuration }}
        
      - name: 'Terraform import multiple resources into state file and Terraform plan'
        working-directory: infrastructure/${{ github.event.inputs.Configuration }}
        env:
          CSF_FILE: ${{ github.event.inputs.CSF_FILE }}
        run: |
          set -euo pipefail

          trim_ws() {
            # trim leading and trailing whitespace from a string
            local s="$1"
            # remove leading whitespace characters
            s="${s#"${s%%[![:space:]]*}"}"
            # remove trailing whitespace characters
            s="${s%"${s##*[![:space:]]}"}"
            print '%s' "$s"
          }
          
          echo "Importing resources from CSV file: $CSF_FILE"
          tail -n +2 "$CSF_FILE" \
            | while IFS=',' read -r resource_name resource_id; do
                echo "resource_name: $resource_name"
                echo "resource_id: $resource_id"

                # trim surrounding whitespace from resource_name while prserving embedded quotes like ["key"]   
                resource_name="$(trim_ws "$resource_name")"
                resource_id="$(trim_ws "$resource_id")"

                #escaping example: [""Storage QUEUE DATA CONTRIBUTOR""] > ["Storage QUEUE DATA CONTRIBUTOR"]
                resource_name="${resource_name//\"\"/\"}"
                echo "resource_name after trimming: $resource_name"}
                # remove one leading quote If present
                resource_name="${resource_name#\"}"
                # remove one trailing quote If present
                resource_name="${resource_name%\"}"
                echo "resource_name after removing leading and trailing quotes: $resource_name"
                
                # Normalize common azure id casing issues
                resource_id="${resource_id//\/resourcegroups\//\/resourceGroups\/}"

                #skip empty and bad lines
                if [[ -z "$resource_name" || -z "$resource_id" ]]; then
                  echo "Skipping empty or bad line: resource_name='$resource_name', resource_id='$resource_id'"
                  continue
                fi

                terraform import -var-file=environments/${{ github.event.inputs.TerraformEnvironment }}/${{ github.event.inputs.TerraformEnvironment }}.tfvars "$resource_name" "$resource_id"
              done



          terraform plan -var-file=environments/${{ github.event.inputs.TerraformEnvironment }}/${{ github.event.inputs.TerraformEnvironment }}.tfvars